Enemy ai
JonathanHunter/GGJ2018 pull request #3
Opened 2018-02-03 23:35 UTC by TahriT

1. I removed enemyfixed  and enemyrandom from the levels. 
2. Only enemyPatrol. 
3. If you don't set a position the enemy is fixed 
4. Shoots and agros only on LOS 
5. Has levels between 1 and 5 which tweaks some parameters 
6. Lose agro after certain time without LOS 
7. Enemy animation are attached to agent speed .

2018-02-04 00:05 UTC, JonathanHunter requested changes

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        public void TargetPlayer()
Make abstract if you want this to be empty

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        public void Chase()
Make abstract if you want this to be empty

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +            // Returns if no points have been set up
why are these comments here?

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        private void FixedUpdate()
why is this here if its empty

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +            //Depricated Moving to On Trigger Stay with Raycast
why is this here? if something is deprecated remove it

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +
remove this extra empty space

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        //Shoots
use xml comments for method summaries ex. /// \<summary> \</summary>

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        // fixed update on raycasts
why is this comment here?

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        // Handels player attacks on enemy
don't put method summaries on Unity methods, put this comment near the code that does this

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        //Active while in range of player
don't put method summaries on Unity methods, put this comment near the code that does this

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +                        //agro animation
what does this comment mean?

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        public Vector3 RandomNavmeshLocation(float radius)
use xml comments for method summaries ex. /// \<summary> \</summary>

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        public static Vector3 RandomNavSphere(Vector3 origin, float dist, int layermask)
use xml comments for method summaries ex. /// \<summary> \</summary>

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        void Start()
remove this if its empty

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        void Update()
remove this if its empty

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +        // Chase player
use xml comments for method summaries ex. /// \<summary> \</summary>

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +    public class EnemyAI : MonoBehaviour
what is this class supposed to do?  if its an AI parent then make it extend Enemy.cs

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +        new public void GotoNextPoint()
don't use 'new'.  If you want to override a method make the method in the parent class virtual then add the keyword override to this.

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +       new  public void Chase()
don't use 'new'.  If you want to override a method make the method in the parent class virtual then add the keyword override to this.

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +            if (dist.magnitude >  agroRange)
remove extra space

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Player/Player.cs
> +
why is this file change here?  don't commit a change unless there is actual content

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +
remove extra line

2018-02-04 00:05 UTC, JonathanHunter commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +
remove extra line

2018-02-04 00:20 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        private void FixedUpdate()
Though it was needed for ray-casting to work properly something you mentioned before. Removing

2018-02-04 00:32 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +                        //agro animation
Place holder for enemy animation from Larry

2018-02-04 00:50 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        public Vector3 RandomNavmeshLocation(float radius)
Fixed https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:50 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        public static Vector3 RandomNavSphere(Vector3 origin, float dist, int layermask)
Fixed https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:50 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        void Start()
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:50 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyAI.cs
> +        void Update()
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:51 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +        new public void GotoNextPoint()
Fixed but please check again
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:51 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +        // Chase player
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:51 UTC, TahriT commented on Assets/Scripts/Character/Enemy/EnemyPatrol.cs
> +       new  public void Chase()
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:52 UTC, TahriT commented on Assets/Scripts/Character/Player/Player.cs
> +
My bad. Was looking for example code of yours. >.<

2018-02-04 00:53 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:53 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:53 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        private void FixedUpdate()
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:54 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +            // Returns if no points have been set up
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:55 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        public void TargetPlayer()
Fixed I think made it virtual https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:55 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        public void Chase()
Fixed I think I made it virtual  
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:55 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        //Shoots
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:55 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        // fixed update on raycasts
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:56 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        // Handels player attacks on enemy
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:56 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +            //Depricated Moving to On Trigger Stay with Raycast
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 00:56 UTC, TahriT commented on Assets/Scripts/Character/Enemy/Enemy.cs
> +        //Active while in range of player
Fixed
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-04 01:00 UTC, TahriT commented
I made the changes but I've got merge conflicts. Not sure what happened. But please review again.
https://github.com/JonathanHunter/GGJ2018/pull/3/commits/7bbc53c24cf9c4d3eb1a7a23ae98e730651850f1

2018-02-07 03:53 UTC, JonathanHunter approved these changes

2018-02-07 03:53 UTC, merged